apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  labels:
    department: cloudengineering
    project: developerautomation
    component: frontend
    app: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
      component: frontend
  template:
    metadata:
      labels:
        department: cloudengineering
        project: developerautomation
        component: frontend
        app: backstage
    spec:
      containers:
      - name: app
        image: 579478677147.dkr.ecr.eu-central-1.amazonaws.com/selfservice/backstage:$(Build.BuildId)
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: app
          protocol: TCP
      resources:
        requests:
          memory: "200Mi"
          cpu: "100m"
        limits:
          memory: "400Mi"
          cpu: "200m"
