catalog:
  - plugins/catalog/**/*
  - plugins/catalog-*/**/*
  - packages/catalog-*/**/*
scaffolder:
  - plugins/scaffolder/**/*
  - plugins/scaffolder-*/**/*
search:
  - plugins/search/**/*
  - plugins/search-*/**/*
  - packages/search-*/**/*
