app:
  title: Backstage Example App
  baseUrl: http://localhost:7000

backend:
  baseUrl: http://localhost:7000
  listen:
    port: 7000
  database:
    client: sqlite3
    connection: ':memory:'

# See README.md in the proxy-backend plugin for information on the configuration format
proxy:
  '/circleci/api':
    target: https://circleci.com/api/v1.1
    changeOrigin: true
    pathRewrite:
      '^/proxy/circleci/api/': '/'
    headers:
      Circle-Token:
        $secret:
          env: CIRCLECI_AUTH_TOKEN

  '/jenkins/api':
    target: http://localhost:8080
    headers:
      Authorization:
        $secret:
          env: JENKINS_BASIC_AUTH_HEADER

organization:
  name: Spotify

techdocs:
  storageUrl: http://localhost:7000/techdocs/static/docs
  requestUrl: http://localhost:7000/techdocs/docs
  generators:
    techdocs: 'docker'

sentry:
  organization: spotify

rollbar:
  organization: spotify
  accountToken:
    $secret:
      env: ROLLBAR_ACCOUNT_TOKEN

newrelic:
  api:
    baseUrl: 'https://api.newrelic.com/v2'
    key: NEW_RELIC_REST_API_KEY

lighthouse:
  baseUrl: http://localhost:3003

kubernetes:
  clusterLocatorMethod: "configMultiTenant"
  clusters: # []
    - url: https://192.168.64.2:8443
      name: minikube
      serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6Img4TUpQaGdWY0FQR2piUHprM050SWpFZWk5TVpvOWt4dEZfa1RwdTlTcUkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InRlc3QtdG9rZW4taHg4OWoiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoidGVzdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjkwMDY4YTZjLTI3Y2EtNDM5Mi1iYmNjLWRmMzM4NjIxN2Y1MSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OnRlc3QifQ.BjXtR3BMrBoTMONeRQwP60DmpHrueRqf3e6knA2aktDyi0KdOTofO5ZxsjiyKkwLRQJxqPgUxhtccTUDVOfHiWx3eqWtnzCESxgYCpjnhZisD-u_cqzyhYHOVLijUWmLDKs1ya3bNnVnfx1XXyrv45mTH76Tis4LXIhLUXGBqoAWeH3IYZHCvkW_cHC_Pnvu1lrzqIbYpTZEYIAfZecQ9lfDBHQsZjRgTx9S3pYiPQ8y-85DJngnCeJg1TjbLoCA17TMcVByG6J-n3K4e9x-Zq7arpiq4vnemmQz7_oYExbALLXQEnDPGexi83N0BSfLOxkKhRY2gQJL7j6n6tnsbw

catalog:
  rules:
    - allow: [Component, API, Group, Template, Location]
  processors:
    github:
      providers:
        - target: https://github.com
          token:
            $secret:
              env: GITHUB_PRIVATE_TOKEN
        #### Example for how to add your GitHub Enterprise instance using the API:
        # - target: https://ghe.example.net
        #   apiBaseUrl: https://ghe.example.net/api/v3
        #   token:
        #     $secret:
        #       env: GHE_PRIVATE_TOKEN
        #### Example for how to add your GitHub Enterprise instance using raw HTTP fetches (token is optional):
        # - target: https://ghe.example.net
        #   rawBaseUrl: https://ghe.example.net/raw
        #   token:
        #     $secret:
        #       env: GHE_PRIVATE_TOKEN
    bitbucketApi:
      username:
        $secret:
          env: BITBUCKET_USERNAME
      appPassword:
        $secret:
          env: BITBUCKET_APP_PASSWORD
    gitlabApi:
      privateToken:
        $secret:
          env: GITLAB_PRIVATE_TOKEN
    azureApi:
      privateToken:
        $secret:
          env: AZURE_PRIVATE_TOKEN

  locations:
    # Backstage example components
    - type: github
      target: https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/all-components.yaml

    # Example component for github-actions
    - type: github
      target: https://github.com/spotify/backstage/blob/master/plugins/github-actions/examples/sample.yaml

    # Example component for techdocs
    - type: github
      target: https://github.com/spotify/backstage/blob/master/plugins/techdocs-backend/examples/documented-component/documented-component.yaml

    # Backstage example APIs
    - type: github
      target: https://github.com/spotify/backstage/blob/master/packages/catalog-model/examples/all-apis.yaml

    # Backstage example templates
    - type: github
      target: https://github.com/spotify/backstage/blob/master/plugins/scaffolder-backend/sample-templates/all-templates.yaml

scaffolder:
  github:
    token:
      $secret:
        env: GITHUB_ACCESS_TOKEN
    visibility: public # or 'internal' or 'private'
  gitlab:
    api:
      baseUrl: https://gitlab.com
      token:
        $secret:
          env: GITLAB_ACCESS_TOKEN

auth:
  providers:
    google:
      development:
        clientId:
          $secret:
            env: AUTH_GOOGLE_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_GOOGLE_CLIENT_SECRET
    github:
      development:
        clientId:
          $secret:
            env: AUTH_GITHUB_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_GITHUB_CLIENT_SECRET
        enterpriseInstanceUrl:
          $secret:
            env: AUTH_GITHUB_ENTERPRISE_INSTANCE_URL
    gitlab:
      development:
        clientId:
          $secret:
            env: AUTH_GITLAB_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_GITLAB_CLIENT_SECRET
        audience:
          $secret:
            env: GITLAB_BASE_URL
    saml:
      entryPoint: 'http://localhost:7001/'
      issuer: 'passport-saml'
    okta:
      development:
        clientId:
          $secret:
            env: AUTH_OKTA_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_OKTA_CLIENT_SECRET
        audience:
          $secret:
            env: AUTH_OKTA_AUDIENCE
    oauth2:
      development:
        clientId:
          $secret:
            env: AUTH_OAUTH2_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_OAUTH2_CLIENT_SECRET
        authorizationUrl:
          $secret:
            env: AUTH_OAUTH2_AUTH_URL
        tokenUrl:
          $secret:
            env: AUTH_OAUTH2_TOKEN_URL
    auth0:
      development:
        clientId:
          $secret:
            env: AUTH_AUTH0_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_AUTH0_CLIENT_SECRET
        domain:
          $secret:
            env: AUTH_AUTH0_DOMAIN
    microsoft:
      development:
        clientId:
          $secret:
            env: AUTH_MICROSOFT_CLIENT_ID
        clientSecret:
          $secret:
            env: AUTH_MICROSOFT_CLIENT_SECRET
        tenantId:
          $secret:
            env: AUTH_MICROSOFT_TENANT_ID
