app:
  title: Backstage Example App
  baseUrl: https://localhost:3000

backend:
  baseUrl: https://localhost:7000
  listen: 0.0.0.0:7000
  cors:
    origin: https://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true

proxy:
  '/circleci/api':
    target: 'https://circleci.com/api/v1.1'
    changeOrigin: true
    pathRewrite:
      '^/proxy/circleci/api/': '/'

organization:
  name: Spotify

techdocs:
  storageUrl: https://techdocs-mock-sites.storage.googleapis.com
