version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: webapp
    container_name: backstage-frontend
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: "postgres:latest"
    container_name: backstage
    environment:
      - POSTGRES_DB=backstage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  backstage-backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    image: backstage-backend
    container_name: backstage-backend
    environment:
      - POSTGRES_HOST=db
      # - DB_SERVER=db
      - POSTGRES_DB=backstage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - GITHUB_TOKEN=${GITHUB_TOKEN} 
      - AUTH_OKTA_CLIENT_ID=${AUTH_OKTA_CLIENT_ID}
      - AUTH_OKTA_CLIENT_SECRET=${AUTH_OKTA_CLIENT_SECRET}
      - AUTH_OKTA_AUDIENCE=${AUTH_OKTA_AUDIENCE}
      - AUTH_GITHUB_CLIENT_ID=${AUTH_GITHUB_CLIENT_ID}
      - AUTH_GITHUB_CLIENT_SECRET=${AUTH_GITHUB_CLIENT_SECRET}
    depends_on:
      - db
    ports:
      - '7000:7000'
volumes:
  postgres_data:
