# Make sure that before you
# run the docker-compose that you have run
# $ yarn docker-build
version: '3'

services:
  backstage:
    image: 'example-backend:latest'
    ports:
      - '7000:7000'
    environment:
      NODE_ENV: development
      GITHUB_PRIVATE_TOKEN: ${GITHUB_PRIVATE_TOKEN}
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      GITHUB_PRIVATE_TOKEN_USER: ${GITHUB_PRIVATE_TOKEN_USER}
      CIRCLECI_AUTH_TOKEN: ${CIRCLECI_AUTH_TOKEN}
