apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: artist-engagement-portal
  title: Artist Engagement Portal
  description: Everything related to artists
  tags:
    - portal
spec:
  owner: team-a
  domain: artists
