services:
  backstage:
    image: tugboatqa/node:lts
    expose: 7000
    default: true
    commands:
      init:
        - yarn install
      build:
        - yarn tsc
        - yarn build --config app-config.yaml --config .tugboat/tugboat.app-config.production.yaml
      update:
        - yarn install
      start:
        # This should be production, but we need to run backend:bundle like the dockerfile does.
        - yarn start-backend --config app-config.yaml --config .tugboat/tugboat.app-config.production.yaml &
