services:
  backstage:
    image: tugboatqa/node:lts
    expose: 7000
    default: true
    commands:
      init:
        - yarn install
      build:
        - yarn tsc
        - yarn build
      update:
        - yarn install
        - env
      start:
        - node packages/backend --config app-config.yaml --config .tugboat/tugboat.app-config.production.yaml &
