services:
  backstage:
    image: tugboatqa/node:lts
    expose: 7000
    default: true
    commands:
      init:
        - yarn install
        - yarn tsc
        - yarn build
      start:
        - yarn start-backend
