version: '3.9'
services:
  backstage-backend:
    build:
      args:
        - app_config_file=app-config.production.yaml
  backstage-frontend:
    build:
      args:
        - app_config_file=app-config.production.yaml

