version: '3.9'
services:
  database:
    image: postgres:latest
    container_name: backstage-db
    ports:
      - "5432:5432"
  backstage-backend:
    depends_on:
      - database         
    image: backstage-backend
    container_name: backend
    build:
      dockerfile: ./packages/backend/Dockerfile
      context: ../
      args:
        - app_config_file=app-config.production.yaml
    ports:
      - '7000:7000'
    links:
      - database
  backstage-frontend:
    depends_on:
      - backstage-backend     
    image: backstage-frontend
    container_name: frontend
    build:
      dockerfile: ./contrib/docker/multi-stage-frontend/Dockerfile
      context: ../
    ports:
      - '3000:80'
  # ubuntu:
  #   image: ubuntu:latest
  #   entrypoint: bash -c
  #   tty: true
  #   command: 
  #   - echo Hello $BACKEND_CORS_ORIGIN  
