version: '3.9'
services:
  database:
    image: postgres:latest
    container_name: backstage-db
    ports:
      - "5432:5432"
    env_file: 
      - .env    
  backstage-backend:
    depends_on:
      - database         
    image: backstage-backend
    container_name: backend
    build:
      dockerfile: ./packages/backend/Dockerfile
      context: ../
    ports:
      - '7000:7000'
    links:
      - database
    env_file: 
      - .env
  backstage-frontend:
    depends_on:
      - backstage-backend     
    image: backstage-frontend
    container_name: frontend
    build:
      dockerfile: ./contrib/docker/multi-stage-frontend/Dockerfile
      context: ../
    ports:
      - '3000:80'
    env_file: 
      - .env
  kafka:
    image: spotify/kafka
    ports:
    - "2181:2181"
    - "9092:9092"
    environment:
      - "ADVERTISED_HOST=localhost"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"