version: '3.9'
services:
  backstage-backend:
    image: backstage-backend
    container_name: backend
  backstage-frontend:
    depends_on:
      - backstage-backend
    image: backstage-frontend
    container_name: frontend

