apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dream11-svc
  description: Dream11 Service
  tags:
    - demo
spec:
  type: website
  owner: sre
  system: sre
  lifecycle: production
  consumesApis: ['component:artist-lookup']
