apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wayback-search
  description: Search of the wayback machine
spec:
  type: service
  lifecycle: production
  owner: team-a
  providesApis:
    - entityRef: wayback-search
      metadata:
        version: '1'
        apis: '/test,/123'
  consumesApis:
    - wayback-archive
