site_name: 'mock-docs'
site_description: 'mock-docs site description'

nav:
  - Home: index.md
  - SubDocs: '!include ./sub-docs/mkdocs.yml'

plugins:
  - techdocs-core

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  