name: Pull Request
on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: Breakpoint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Testing
        uses: trunk-io/breakpoint@v1
        with:
          breakpoint-id: run-tests
          run: exit 1
          trunk-token: ${{ secrets.TRUNK_DEBUGGER_TOKEN }}
          org: matts_org
