name: Tugboat E2E Tests
on: deployment_status
jobs:
  set-pending:
    if: github.event.deployment_status.state != 'success' && github.event.deployment_status.state != 'failed'
    name: Run tests against Tugboat
    runs-on: ubuntu-latest
    steps:
      # Set an initial commit status message to indicate that the tests are
      # running.
      - name: set pending status
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GH_SERVICE_ACCOUNT_TOKEN}}
          debug: true
          script: |
            return github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'pending',
              context: 'Backstage Tugboat E2E Tests',
              description: 'Running tests',
              target_url: "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
            });

  run-tests:
    # Only run after a successful Tugboat deployment.
    if: github.event.deployment_status.state == 'success'
    name: Run tests against Tugboat
    runs-on: ubuntu-latest
    steps:
      # Set an initial commit status message to indicate that the tests are
      # running.
      - name: set pending status
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GH_SERVICE_ACCOUNT_TOKEN}}
          debug: true
          script: |
            return github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'pending',
              context: 'Backstage Tugboat E2E Tests',
              description: 'Running tests',
              target_url: "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
            });

      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      # This is required because the environment_url param that Tugboat uses
      # to tell us where the preview is located isn't supported unless you
      # specify the custom Accept header when getting the deployment_status,
      # and GitHub actions doesn't do that by default. So instead we have to
      # load the status object manually and get the data we need.
      # https://developer.github.com/changes/2016-04-06-deployment-and-deployment-status-enhancements/
      - name: get deployment status
        id: get-status-env
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GH_SERVICE_ACCOUNT_TOKEN}}
          result-encoding: string
          script: |
            const result = await github.repos.getDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: context.payload.deployment.id,
              status_id: context.payload.deployment_status.id,
              headers: {
                'Accept': 'application/vnd.github.ant-man-preview+json'
              },
            });
            console.log(result);
            return result.data.environment_url;
      - name: echo tugboat preview url
        run: |
          echo ${{steps.get-status-env.outputs.result}}
          # The first time you hit a Tugboat URL it can take a while to load, so
          # we visit it once here to prime it. Otherwise the very first test
          # will often timeout.
          curl ${{steps.get-status-env.outputs.result}}
