name: Microsite
on:
  pull_request:
    paths:
      - '.github/workflows/verify_microsite.yml'
      - 'microsite/**'
      - 'beps/**'
      - 'mkdocs.yml'
      - 'docs/**'

permissions:
  contents: read

jobs:
  build-microsite:
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_OPTIONS: --max-old-space-size=8192
      DOCUSAURUS_SSR_CONCURRENCY: 5

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the version you need

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install MkDocs dependencies
        run: pip install mkdocs mkdocs-techdocs-core

      - name: Install Yarn dependencies
        run: yarn install --immutable
        working-directory: microsite

      - name: Build API reference
        run: yarn build:api-docs

      - name: Build MkDocs for TechDocs
        run: mkdocs build --strict

      - name: Verify yarn dependency duplicates
        run: node scripts/verify-lockfile-duplicates.js

      - name: Check formatting with Prettier
        run: yarn prettier:check
        working-directory: microsite

      - name: Build microsite
        run: yarn build
        working-directory: microsite
