name: Verify FOSSA

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3; hash pinned for build security
      - name: Run FOSSA analysis for license compliance and security
        uses: fossas/fossa-action@f61a4c0c263690f2ddb54b9822a719c25a7b608f #v1.3.1; hash pinned for build security
        with:
          api-key: 9ee7e8893660832a7387dcc32377fb61
